Added OS identification, prevents scripts intended for other OS's from executing.

diff --git a/bin/apt b/bin/apt
--- a/bin/apt
+++ b/bin/apt
@@ -347,6 +347,19 @@ if ! OSsupported; then
     exit 1
 fi
 
+# Ensure that only Debian/Ubuntu based distros can execute this script
+case "$(OSType)" in
+    "$OS_DEBIAN_NAME"|"$OS_UBUNTU_NAME");;
+    *)
+        logMsg "ERROR: Only Debain/Ubuntu based distros are allowed to execute this script." 0
+        logMsg "OS Information" 0
+        logMsg "==============" 0
+        logMsg "$(OSInfo)" 0
+        exit 1 
+        ;;
+esac
+
+
 logMsg "Updating Package Repo Lists..." 0
 
 updateApt 2>&1 | \
diff --git a/bin/brew b/bin/brew
--- a/bin/brew
+++ b/bin/brew
@@ -392,6 +392,19 @@ if ! OSsupported; then
     exit 1
 fi
 
+# Ensure that only Debian/Ubuntu based distros can execute this script
+case "$(OSType)" in
+    "$OS_MACOS_NAME");;
+    *)
+        logMsg "ERROR: This script can only be executed using macOS." 0
+        logMsg "OS Information" 0
+        logMsg "==============" 0
+        logMsg "$(OSInfo)" 0
+        exit 1 
+        ;;
+esac
+
+
 logMsg "Installing Homebrew... (this may take a while)" 0
 
 if isBrewInstalled; then
