Bug Fix: Invalid log_ID provided by '-l' option now causes error, not correction.

diff --git a/bin/bashShell b/bin/bashShell
--- a/bin/bashShell
+++ b/bin/bashShell
@@ -29,10 +29,11 @@ shellChangeSuccess=false
 # Minimum version of Bash required for this script to run
 declare -ri MIN_BASH_VERS=3
 
+# User's shells file
 declare -r SHELLS_FILE="/etc/shells"
 
 usage() {
-    local script=${0##*/}
+    local script="${0##*/}"
     local buffer=""
     local file=""
 
@@ -180,7 +181,7 @@ fi
 
 # Asks for root permissions
 sudo true
-if [[ "$?" -ne 0 ]]; then
+if [[ "$?" -ne "0" ]]; then
     echo "ERROR: Failed to provide sudo password."
     exit 1
 fi
@@ -200,10 +201,10 @@ if ! "$logProvided"; then
 fi
 
 # Verify Log Identifier, exit if invalid
-logID="$(createLogID)"
 if ! validLogID "$logID"; then
     if ! "$silentMode"; then
         echo "ERROR: Invalid log_ID generated/provided. See usage (-h option) for correct format."
+        usage
     fi
     exit 1;
 fi
@@ -218,8 +219,8 @@ fi
 
 # Invalid option / argument was provided, display Help Message and exit
 if "$invalidArg"; then
-    logMsg "ERROR: Invalid option/argument provided!\n" 0
-    logMsg "$(usage ${0})" 0
+    logMsg "ERROR: Invalid option/argument provided.\n" 0
+    logMsg "$(usage "$0")" 0
     exit 1
 fi
 
