Updated loggering invocation and added minimum Bash version support.

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -16,11 +16,15 @@ invalidArg=false
 displayHelp=false
 logProvided=false
 
-logID=""	# Log Identifier
+# Log Identifier
+logID=""
+
+# Minimum version of Bash required for this script to run
+declare -ri MIN_BASH_VERS=3
 
 # Number of operations necessary to install all dotfiles
 declare -i operationsCompleted=0
-declare -i TOTAL_OPERATIONS=7
+declare -ri TOTAL_OPERATIONS=7
 
 # Dotfiles and corresponding directories
 DOTFILES_DIR="$HOME/.dotfiles/shell"
@@ -78,24 +82,21 @@ usage() {
     echo
     echo "    If multiple '-l' options are provided, only the last log_ID will be used; for example:"
     echo
-    echo "        ./dotfiles -s -l log_05-17-2020_13-17-37 -l log_05-17-2020_14-58-09 -l log_05-18-2020-00-01-48"
+    echo "        ./$script -s -l log_05-17-2020_13-17-37 -l log_05-17-2020_14-58-09 -l log_05-18-2020-00-01-48"
     echo "                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^"
     echo "                                                                            Only this log_ID will be used"
 }
 
 
 exitMessage() {
-    echo
     echo "$operationsCompleted of $TOTAL_OPERATIONS Operations Successfully Completed."
-    echo
-    echo "The last successfully completed operation is shown above (If any)."
-    echo
-    echo "The logged output from running this script can be found at: $LOG_DIR/$logID/$LOG_DOTFILES\n"
+    echo "The last operation that failed is shown above (ff any)."
+    echo "The logged output can be found at: $LOG_DIR/$logID/$LOG_DOTFILES"
 }
 
 
 parseArgs() {
-    while [[ ! OPTIND -gt "$#" ]]; do
+    while [[ ! "$OPTIND" -gt "$#" ]]; do
         while getopts ":hsl:" opt; do
             case $opt in
                 s)  # Silent Mode selected
@@ -115,7 +116,7 @@ parseArgs() {
         done
 
         # Invalid Arguments are skipped.
-        if [[ ! OPTIND -gt "$#" ]]; then
+        if [[ ! "$OPTIND" -gt "$#" ]]; then
             invalidArg=true
             (( ++OPTIND ))
         fi
@@ -130,6 +131,24 @@ shouldPrint() {
         echo false;
     fi
 }
+
+
+logMsg() {
+    logDotfiles "$logID" "$1" "$2" "$(shouldPrint)"
+}
+
+
+# Verifies that Bash meets the version requirements necessary to execute the
+# contents of this script, without error.
+if [ "${BASH_VERSINFO:-0}" -lt "$MIN_BASH_VERS" ]; then
+    printf "ERROR: Bash Version 3 or higher is required, your version is " >&2
+    if [ -z "$BASH_VERSION" ]; then
+        printf "(unknown).\n" >&2
+    else
+        printf "$BASH_VERSION.\n" >&2
+    fi
+    exit 1
+fi
 
 
 ###############################################################################
@@ -170,8 +189,8 @@ fi
 
 # Invalid option / argument was provided, display Help Message and exit
 if $invalidArg; then
-    logDotfiles "$logID" "ERROR: Invalid option/argument provided!\n" "$(shouldPrint)"
-    logDotfiles "$logID" "$(usage $0)" "$(shouldPrint)"
+    logMsg "ERROR: Invalid option/argument provided!\n" 0
+    logMsg "$(usage $0)" 0
     exit 1
 fi
 
@@ -180,10 +199,12 @@ fi
 #								Install Dotfiles
 ###############################################################################
 
-logDotfiles "$logID" "Creating file '$DOTFILES_DIR/$PRIVATE_DOTFILE'...\n" \
-            "$(shouldPrint)"
+# Creates a 'private' file, intended to store private commands and credentials.
+# The contents of this file will not be commited, and is sourced onlh by the
+# bashrc file.
+logMsg "Creating file '$DOTFILES_DIR/$PRIVATE_DOTFILE'...\n" 0
 if [[ -f "$DOTFILES_DIR/$PRIVATE_DOTFILE" ]]; then
-    logDotfiles "$logID" "    File already exists. (Success)\n\n" "$(shouldPrint)"
+    logMsg "File already exists. (Success)\n" 1
     (( ++operationsCompleted ))
 else
     rm -rf "$DOTFILES_DIR/$PRIVATE_DOTFILE"
@@ -200,46 +221,42 @@ else
 __EOF__
     ) > "$DOTFILES_DIR/$PRIVATE_DOTFILE"
     if [[ ! -f "$DOTFILES_DIR/$PRIVATE_DOTFILE" ]]; then
-        logDotfiles "$logID" \
-                    "    Failed to create '$DOTFILES_DIR/$PRIVATE_DOTFILE'.\n\n" \
-                    "$(shouldPrint)"
-        logDotfiles "$logID" "$(exitMessage)" "$(shouldPrint)"
+        logMsg "Failed to create '$DOTFILES_DIR/$PRIVATE_DOTFILE'. (Failed)\n" 1
+        logMsg "$(exitMessage)" 0
         exit 1
     else
-        logDotfiles "$logID" "Completed.\n\n" "$(shouldPrint)"
+        logMsg "Log created. (Success)\n" 1
         (( ++operationsCompleted ))
     fi
 fi
 
+logMsg "Creating Symbolic Links to relevant dotfiles in directory '$HOME'...\n" 0
 
-logDotfiles "$logID" \
-            "Creating Symbolic Links to relevant dotfiles in directory '$HOME'...\n" \
-            "$(shouldPrint)"
-
-# Shell Dotfiles
+# Installing Shell Dotfiles
+symlinkMsg="Symlink: ${HOME}/.${dotfile} -> ${DOTFILES_DIR}/${dotfile}"
 for dotfile in "${DOTFILES[@]}"; do
-    symlinkMsg="Symlink: ${HOME}/.${dotfile} -> ${DOTFILES_DIR}/${dotfile}"
     if ln -sf "${DOTFILES_DIR}/${dotfile}" "${HOME}/.${dotfile}"; then
-        logDotfiles "$logID"  "    $symlinkMsg (Success)\n" "$(shouldPrint)"
+        logMsg  "$symlinkMsg (Success)\n" 1
         (( ++operationsCompleted ))
     else
-        logDotfiles "$logID" "$symlinkMsg (Failed)\n" "$(shouldPrint)"
-        logDotfiles "$logID" "$(exitMessage)" "$(shouldPrint)"
+        logMsg "$symlinkMsg (Failed)\n" 1
+        logMsg "$(exitMessage)" 0
         exit 1
     fi
 done
 
-# Config Dotfiles
+# Installing Config Dotfiles
+symlinkMsg="Symlink: ${HOME}/.${dotfile##*/} -> ${CONFIG_DOTFILES_DIR}/${dotfile}"
 for dotfile in "${CONFIG_DOTFILES[@]}"; do
-    symlinkMsg="Symlink: ${HOME}/.${dotfile##*/} -> ${CONFIG_DOTFILES_DIR}/${dotfile}"
     if ln -sf "${CONFIG_DOTFILES_DIR}/${dotfile}" "${HOME}/.${dotfile##*/}"; then
-        logDotfiles "$logID" "    $symlinkMsg (Success)\n" "$(shouldPrint)"
+        logMsg "$symlinkMsg (Success)\n" 1
         (( ++operationsCompleted ))
     else
-        logDotfiles "$logID"  "    $symlinkMsg (Failed)\n" "$(shouldPrint)"
-        logDotfiles "$logID" "$(exitMessage)" "$(shouldPrint)"
+        logMsg  "$symlinkMsg (Failed)\n" 1
+        logMsg "$(exitMessage)" 0
         exit 1
     fi
 done
 
-logDotfiles "$logID" "$(exitMessage)" "$(shouldPrint)"
+
+logMsg "$(exitMessage)" 0
