Added more command line options; refactored dotfiles_get_repo function.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -29,17 +29,24 @@ fi
 
 
 # Global Constants
-readonly DOTFILES_DIR="${HOME}/.dotfiles_temp"
+readonly DOTFILES_SYMLINK_LINK_NAME='.dotfiles_temp'
+readonly DOTFILES_SYMLINK_DIR_NAME='dotfiles'   # LINK_NAME -> DIR_NAME
+readonly DOTFILES_PARENT_DIR="${HOME}"
+readonly DOTFILES_DIR="${DOTFILES_PARENT_DIR}/${DOTFILES_SYMLINK_LINK_NAME}"
+         DOTFILES_INSTALL_PARENT_DIR='' # Set readonly after parsing arguments
+         DOTFILES_INSTALL_DIR=''        # Set readonly after parsing arguments
+readonly DOTFILES_TARBALL='/tmp/dotfiles.tar.gz'
 readonly DOTFILES_GIT_TARBALL='https://github.com/llovely/dotfiles/tarball/main'
 readonly DOTFILES_GIT_REMOTE='https://github.com/llovely/llovely/dotfiles.git'
-INSTALL_ARG_ERROR='false'     # Set to readonly after parsing arguments
-INSTALL_ARG_HELP='false'      # Set to readonly after parsing arguments
-INSTALL_ARG_FORCE='false'     # Set to readonly after parsing arguments
-INSTALL_ARG_SYNC='false'      # Set to readonly after parsing arguments
-INSTALL_ARG_PACKAGES='true'   # Set to readonly after parsing arguments
-INSTALL_ARG_BASH_EXEC=''      # Set to readonly after parsing arguments
-INSTALL_ARG_DOTFILES='true'   # Set to readonly after parsing arguments
-INSTALL_OS_TYPE=''            # Set to readonly after being set
+INSTALL_ARG_ERROR='false'           # Set readonly after parsing arguments
+INSTALL_ARG_HELP='false'            # Set readonly after parsing arguments
+INSTALL_ARG_FORCE='false'           # Set readonly after parsing arguments
+INSTALL_ARG_SYNC='false'            # Set readonly after parsing arguments
+INSTALL_ARG_PACKAGES='true'         # Set readonly after parsing arguments
+INSTALL_ARG_BASH_EXEC=''            # Set readonly after parsing arguments
+INSTALL_ARG_CONFIG='true'           # Set readonly after parsing arguments
+INSTALL_ARG_INSTALL_DIR='false'     # Set readonly after parsing arguments
+INSTALL_OS_TYPE=''                  # Set readonly after being set
 
 
 # Globals
@@ -63,9 +70,23 @@ Description:
 
 Options:
 
-  -h, --help
-  -f, --force
-  -b, --bash-exec
+  -h, --help                    Prints this help message and exit.
+  -f, --force                   Forcibly installs '.dotfiles' directory in one's
+                                in one's \$HOME directory, overwriting any
+                                existing Dotfiles directory present;
+                                any changes made prior will be
+                                lost. If a '.dotfiles' symbolic link is,
+                                encountered. only the symbolic link will be
+                                deleted.
+                                will be delted
+      --no-symlink              Does not create a symbolic link to the Dotfiles
+                                directory, when installing.
+                                This option is ignored if --install-dir is
+                                provided.
+      --install-dir <path>      Path to install Dotfiles directory.
+      --default-shell <path>
+      --no-packages
+      --sync
 __EOF__
 }
 
@@ -109,7 +130,7 @@ function out_msg() {
 
 
 ################################################################################
-# Installs Homebrew.
+# Verifies that Homebrew is installed.
 # Globals:
 #   INSTALL_SCRIPT_BREW_INSTALLED
 # Arguments:
@@ -119,13 +140,15 @@ function out_msg() {
 # Returns:
 #   0 if Homebrew installed successfully; otherwise, non-zero on error.
 ################################################################################
-function install_homebrew() {
-  out_msg "\nInstalling Homebrew..."
-  if brew::installed &> /dev/null; then
-    out_msg "Homebrew is already installed!"
-  else
+function verify_homebrew() {
+  out_msg "\nVerifying if Homebrew is installed..."
+
+  if ! brew::installed &> /dev/null; then
+    out_msg "\nHomebrew not found, installing..."
     brew::install || return 1
     out_msg "Homebrew is installed!"
+  else
+    out_msg "Homebrew is already installed!"
   fi
 
   INSTALL_SCRIPT_BREW_INSTALLED='true'
@@ -146,7 +169,7 @@ function install_homebrew() {
 function verify_xcode() {
   local xcode_path
 
-  out_msg "\nVerifying Xcode Command Line Tools..."
+  out_msg "\nVerifying if Xcode Command Line Tools are installed..."
 
   xcode_path="$(xcode::get_path)"
   (( $? != 0 )) && return 1
@@ -200,12 +223,14 @@ function verify_xcode() {
 function verify_apt() {
   err_msg "ERROR: ${FUNCNAME[0]}() failed. NOT IMPLEMENTED."
   return 1
+
+  INSTALL_SCRIPT_APT_INSTALLED='true'
 }
 
 
 ################################################################################
 # Verifies that the associated package managers of the supported OS's are
-# present and have access to necessary packages to function properly.
+# present and have access to necessary utilities to function properly.
 # Globals:
 #   FUNCNAME
 #   INSTALL_OS_TYPE
@@ -218,21 +243,20 @@ function verify_apt() {
 #   Writes installation/verification steps to stdout; writes error message(s) to
 #   stderr.
 # Returns:
-#   0 if package manager present with associated helper utilities; otherwise,
-#   non-zero on error.
+#   0 if package manager and utilities present; otherwise, non-zero on error.
 ################################################################################
-function verify_pkg_mgr_and_helper_utils() {
+function verify_pkg_mgr_and_utils() {
   case "${INSTALL_OS_TYPE}" in
     "${OS_NAME_MACOS}")
-      install_homebrew || exit 1
-      verify_xcode || exit 1
+      verify_homebrew || return 1
+      verify_xcode || return 1
       ;;
     "${OS_NAME_DEBIAN}"|"${OS_NAME_UBUNTU}")
-      verify_apt || exit 1
+      verify_apt || return 1
       ;;
     *) # Unsupported OS type
       err_msg "ERROR: ${FUNCNAME[0]}() failed. Unknown OS type encountered."
-      exit 1
+      return 1
       ;;
   esac
 }
@@ -271,6 +295,7 @@ function install_git() {
   esac
 
   out_msg "git is installed and ready for use!"
+  INSTALL_SCRIPT_GIT_INSTALLED='true'
 }
 
 
@@ -278,9 +303,16 @@ function install_git() {
 # Downloads and unpacks Dotfile repository tarball into created Dotfiles
 # directory.
 # Globals:
-#   HOME
 #   FUNCNAME
+#   INSTALL_ARG_FORCE
+#   INSTALL_ARG_INSTALL_DIR
+#   DOTFILES_SYMLINK_LINK_NAME
+#   DOTFILES_SYMLINK_DIR_NAME
 #   DOTFILES_DIR
+#   DOTFILES_PARENT_DIR
+#   DOTFILES_INSTALL_DIR
+#   DOTFILES_INSTALL_PARENT_DIR
+#   DOTFILES_TARBALL
 #   DOTFILES_GIT_TARBALL
 # Arguments:
 #   None
@@ -288,92 +320,129 @@ function install_git() {
 #   Writes download and setup steps to stdout; writes error message(s) to
 #   stderr.
 # Returns:
-#   0 if Dotfiles repo unpacked successfully; otherwise, non-zero on error.
+#   0 if Dotfiles repo unpacked and removed successfully; otherwise, non-zero
+#   on error.
 ################################################################################
 function dotfiles_get_repo() {
-  local -r dotfiles_dir='dotfiles'
-  local -r dotfiles_tar='/tmp/dotfiles.tar.gz'
-  local curr_dir
+  out_msg "\nVerifying if '${DOTFILES_SYMLINK_LINK_NAME}' exists in" \
+          "'${DOTFILES_PARENT_DIR}' directory..."
 
-  out_msg "\nVerifying if '${DOTFILES_DIR}' directory is present..."
-
-  # Determines current working directory.
-  curr_dir="$(pwd -P 2> /dev/null)"
-  if (( $? != 0 )); then
-    err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to determine current" \
-            "working directory."
+  # Removes existing dotfiles directory
+  if [[ -d "${DOTFILESD_DIR}" ]]; then
+    if [[ "${INSTALL_ARG_FORCE}" != 'true' ]]; then
+      out_msg "'${DOTFILES_SYMLINK_LINK_NAME}' directory already exists!" \
+              "Directory will not be overwritten; moving on."
+      return 0
+    else
+      out_msg "Removing '${DOTFILES_SYMLINK_LINK_NAME}' directory..."
+    fi
+  # Removes exising dotfiles symbolic link
+  elif [[ -L "${DOTFILES_DIR}" ]]; then
+    if [[ -e "${DOTFILES_DIR}" && "${INSTALL_ARG_FORCE}" != 'true' ]]; then
+      out_msg "'${DOTFILES_SYMLINK_LINK_NAME}' already exists as an unbroken" \
+              "symbolic link! Link will not be overwritten; moving on."
+      return 0
+    else
+      out_msg "Removing '${DOTFILES_SYMLINK_LINK_NAME}' symbolic link..."
+    fi
+  # Removes any file with the same name as the dotfiles directory/synlink
+  else
+    out_msg "Removing any file with the name '${DOTFILES_SYMLINK_LINK_NAME}'..."
+  fi
+  if ! rm -rvf "${DOTFILES_DIR}"; then
+    err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to remove" \
+            "'${DOTFILES_SYMLINK_LINK_NAME}'."
     return 1
   fi
+  out_msg "'${DOTFILES_SYMLINK_LINK_NAME}' successfully removed!"
 
-  # Checks if Dotfiles directory is already present (even as a symlink)
-  if ! [[ -d "${DOTFILES_DIR}" || -L "${DOTFILES_DIR}" ]]; then
-    out_msg "'${DOTFILES_DIR}' directory is not present!"
 
-    # Create Dotfiles directory
-    if [[ "${curr_dir}}" != "${HOME}" ]]; then
-      out_msg "HOME directory is not the current working directory; creating"
-              "'${dotfiles_dir}' directory in '${curr_dir}'..."
-      if ! mkdir "${dotfiles_dir}"; then
-        err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to create" \
-                "'${curr_dir}/${dotfiles_dir}' directory."
-        return 1
-      fi
-      out_msg "'${curr_dir}/${dotfiles_dir}' directory created!"
-
-      out_msg "Creating symlink from '"${curr_dir}/${dotfiles_dir}"' ->" \
-              "'"${DOTFILES_DIR}"'..."
-      if ! ln -sf "${curr_dir}/${dotfiles_dir}" "${DOTFILES_DIR}"; then
-        err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to create symlink."
-        return 1
-      fi
-      out_msg "Symlink successfully created!"
+  # Removes symlink destination directory, if needed
+  if [[ "${INSTALL_ARG_INSTALL_DIR}" == 'true' ]]; then
+    out_msg "Installation directory provided; verifying if " \
+            "'${DOTFILES_SYMLINK_DIR_NAME}' directory exists in" \
+            "'${DOTFILES_INSTALL_PARENT_DIR}' directory..."
+    if [[ -d "${DOTFILES_INSTALL_DIR}" \
+          && "${INSTALL_ARG_FORCE}" != 'true' ]]; then
+      out_msg "'${DOTFILES_SYMLINK_DIR_NAME}' directory already exists!" \
+              "Directory will not be overwritten; moving on."
     else
-      out_msg "Creating '.dotfiles' directory in '${HOME}' directory..."
-      if ! mkdir "${DOTFILES_DIR}"; then
-        err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to create" \
-                "'${DOTFILES_DIR}' directory."
+      if [[ -d "${DOTFILES_INSTALL_DIR}" ]]; then
+        out_msg "Removing '${DOTFILES_SYMLINK_DIR_NAME}' directory..."
+      else
+        out_msg "Removing any file with the name" \
+                "'${DOTFILES_SYMLINK_DIR_NAME}'..."
+      fi
+      if ! rm -rvf "${DOTFILES_INSTALL_DIR}"; then
+        err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to remove" \
+                "'${DOTFILES_SYMLINK_DIR_NAME}'."
         return 1
       fi
-      out_msg "'${DOTFILES_DIR}' directory created!"
+      out_msg "'${DOTFILES_SYMLINK_DIR_NAME}' successfully removed!"
     fi
-    out_msg "Dotfiles directory can be accessed from '${DOTFILES_DIR}'."
-
-
-    # Download Dotfiles tarball
-    out_msg "Downloading Dotfiles repository tarball from" \
-            "'${DOTFILES_GIT_TARBALL}'..."
-    if curl -fsSL ${DOTFILES_GIT_TARBALL} -o "${dotfiles_tar}"; then
-      err_msg "ERROR: ${FUNCNAME[0]}() failed. Failed to obtain" \
-              "Dotfiles repository tarball."
-      return 1
-    fi
-    out_msg "Dotfiles tarball downloaded successfully; tarball found at" \
-            "'${dotfiles_tar}'."
-
-
-    # Unpack Dotfiles tarball into Dotfiles directory
-    out_msg "Unpacking contents of '${dotfiles_tar}' into '${DOTFILES_DIR}'..."
-    tar -zxf "${dotfiles_tar}" --strip-components 1 -C "${DOTFILES_DIR}"
-    if (( $? != 0 )); then
-      err_msg "ERROR: ${FUNCNAME[0]}() failed. Failed to unpack tarball" \
-              "'${dotfiles_tar}' into '${DOTFILES_DIR}'."
-      return 1
-    fi
-    out_msg "Tarball successfully unpacked!"
-
-
-    # Remove the downloaded Dotfiles tarball
-    out_msg "Deleting tarball '${dotfiles_tar}'..."
-    if ! rm -rf "${dotfiles_tar}" 2> /dev/null; then
-      err_msg "ERROR: ${FUNCNAME[0]}() failed. Failed to delete" \
-              "'${dotfiles_tar}'."
-      return 1
-    fi
-    out_msg "Tarball successfully deleted!"
-    return 0
   fi
 
-  out_msg "'${DOTFILES_DIR}' directory is already present!"
+
+  # Create dotfiles directory and/or symlink to it
+  if [[ "${INSTALL_ARG_INSTALL_DIR}" == 'true' ]]; then
+    if [[ ! -d "${DOTFILES_INSTALL_DIR}" ]]; then
+      out_msg "Creating '${DOTFILES_SYMLINK_DIR_NAME}' directory in" \
+              "'${DOTFILES_INSTALL_PARENT_DIR}' directory..."
+      if ! mkdir -vp "${DOTFILES_INSTALL_DIR}"; then
+        err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to create" \
+                "'${DOTFILES_SYMLINK_DIR_NAME}' directory."
+        return 1
+      fi
+      out_msg "'${DOTFILES_SYMLINK_DIR_NAME}' directory created!"
+    fi
+    out_msg "Creating symbolic link from '${DOTFIELS_DIR}' (LINK) ->" \
+            "'${DOTFILES_INSTALL_DIR}' (TARGET)..."
+    if ! ln -sf "${DOTFILES_INSTALL_DIR}" "${DOTFILES_DIR}"; then
+      err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to create symbolic" \
+              "link '${DOTFIELS_DIR}'."
+      return 1
+    fi
+    out_msg "Symbolic link '${DOTFIELS_DIR}' successfully created!"
+  else
+    out_msg "Creating '${DOTFILES_SYMLINK_LINK_NAME}' directory in" \
+            "'${DOTFILES_PARENT_DIR}' directory..."
+    if ! mkdir -vp "${DOTFILES_DIR}"; then
+      err_msg "ERROR: ${FUNCNAME[0]}() failed. Unable to create" \
+              "'${DOTFILES_SYMLINK_LINK_NAME}' directory."
+      return 1
+    fi
+    out_msg "'${DOTFILES_SYMLINK_LINK_NAME}' directory created!"
+  fi
+
+
+  # Download Dotfiles tarball
+  out_msg "Downloading Dotfiles tarball from '${DOTFILES_GIT_TARBALL}'..."
+  if ! curl -fsSL ${DOTFILES_GIT_TARBALL} -o "${DOTFILES_TARBALL}"; then
+    err_msg "ERROR: ${FUNCNAME[0]}() failed. Failed to download Dotfiles" \
+            "tarball."
+    return 1
+  fi
+  out_msg "Dotfiles tarball downloaded successfully! Tarball located at: " \
+          "'${DOTFILES_TARBALL}'"
+
+
+  # Unpack Dotfiles tarball into Dotfiles directory
+  out_msg "Unpacking tarball '${DOTFILES_TARBALL}' into '${DOTFILES_DIR}'..."
+  tar -zxf "${DOTFILES_TARBALL}" --strip-components 1 -C "${DOTFILES_DIR}"
+  if (( $? != 0 )); then
+    err_msg "ERROR: ${FUNCNAME[0]}() failed. Failed to unpack tarball."
+    return 1
+  fi
+  out_msg "Tarball successfully unpacked!"
+
+
+  # Remove the downloaded Dotfiles tarball
+  out_msg "Removing tarball '${DOTFILES_TARBALL}'..."
+  if ! rm -rvf "${DOTFILES_TARBALL}"; then
+    err_msg "ERROR: ${FUNCNAME[0]}() failed. Failed to remove tarball."
+    return 1
+  fi
+  out_msg "Tarball successfully removed!"
 }
 
 
@@ -504,7 +573,18 @@ function dotfiles_sync_repo() {
 # Entry point of this script.
 function main() {
 
-  # Parses command line arguments
+  # Parses command line arguments (getopts was not used since it does not
+  # support long arguments, and getopt was not used since the default version
+  # provided on macOS also does not support long arguments).
+
+
+  # Parses command line arguments (getopts was not used since it does not
+  # support long arguments, and getopt was not used since the default version
+  # provided on macOS also does not support long arguments).
+
+  # Parses command line arguments. getopts and getopt (the default verion on
+  # macOS) were not used since both do not support long options, and the
+  # GNU getopt version cannot be installed until after parsing these arguments.
   local opt
   while (( $# > 0 )); do
     opt="$1"
@@ -515,28 +595,65 @@ function main() {
       -f|--force)
         INSTALL_ARG_FORCE='true'
         ;;
-      -b|--bash-exec)
+      --install-dir)
         shift
         if (( $# == 0 )); then
-          err_msg "ERROR: ${opt} option expected a path arguement."
+          err_msg "ERROR: '${opt}' option -- Expected a directory path"
+                  "argument."
           INSTALL_ARG_ERROR='true'
           break
         fi
         case "$1" in
           -*|--*)
-            err_msg "ERROR: ${opt} option expected a path arguement."
+            err_msg "ERROR: '${opt}' option -- Expected a directory path" \
+                    "arguement."
             INSTALL_ARG_ERROR='true'
             break
             ;;
           *)
-            if [[ -z "$1" ]]; then
-              err_msg "ERROR: ${opt} option provided with empty string."
+            if [[ ! -d "$1" ]]; then
+              err_msg "ERROR: '${opt}' option -- '$1' argument is not a" \
+                      "directory path."
+              INSTALL_ARG_ERROR='true'
+              break
+            elif [[ "$1" == */ ]]; then
+              err_msg "ERROR: '${opt}' option -- '$1' argument cannot end" \
+                      "with a '/'."
+              INSTALL_ARG_ERROR='true'
+              break
+            else
+              INSTALL_ARG_INSTALL_DIR='true'
+              DOTFILES_INSTALL_PARENT_DIR="$1"
+              DOTFILES_INSTALL_DIR="${1}/${DOTFILES_SYMLINK_DIR_NAME}"
+            fi
+            ;;
+        esac
+        ;;
+      --default-shell)
+        shift
+        if (( $# == 0 )); then
+          err_msg "ERROR: '${opt}' option -- Expected a file path arguement."
+          INSTALL_ARG_ERROR='true'
+          break
+        fi
+        case "$1" in
+          -*|--*)
+            err_msg "ERROR: '${opt}' option -- Expected a file path arguement."
+            INSTALL_ARG_ERROR='true'
+            break
+            ;;
+          *)
+            if ! [[ -f "$1" && -x "$1" ]]; then
+              err_msg "ERROR: '${opt}' option -- "
               INSTALL_ARG_ERROR='true'
               break
             fi
             INSTALL_ARG_BASH_EXEC="$1"
             ;;
         esac
+        ;;
+      --no-config)
+        INSTALL_ARG_CONFIG='false'
         ;;
       --no-packages)
         INSTALL_ARG_PACKAGES='false'
@@ -557,13 +674,20 @@ function main() {
     esac
     shift
   done
+  if [[ "${INSTALL_ARG_INSTALL_DIR}" == 'true' ]]; then
+    if [[ "${DOTFILES_INSTALL_PARENT_DIR}" -ef "${HOME}" ]]; then
+      INSTALL_ARG_INSTALL_DIR='false'
+      DOTFILES_INSTALL_PARENT_DIR=''
+    fi
+  fi
   readonly INSTALL_ARG_ERROR
   readonly INSTALL_ARG_HELP
   readonly INSTALL_ARG_FORCE
   readonly INSTALL_ARG_SYNC
   readonly INSTALL_ARG_PACKAGES
   readonly INSTALL_ARG_BASH_EXEC
-  readonly INSTALL_ARG_DOTFILES
+  readonly INSTALL_ARG_CONFIG
+  readonly INSTALL_ARG_INSTALL_DIR
 
 
   # Displays usage information when invalid option(s) provided
@@ -615,7 +739,7 @@ function main() {
 
   # Ensures that the OS package manager is present and has all necessary
   # packages/utilities to function properly
-  verify_pkg_mgr_and_helper_utils || exit 1
+  verify_pkg_mgr_and_utils || exit 1
 
 
   # Installs git
